SSO/Pages/Admin/ForgotPassword.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SSO.Models.DTOs;

namespace SSO.Pages.Admin
{
    public class ForgotPasswordModel : PageModel
    {
        [ModelBinder]
        public SignUpDTO Model { get; set; }

        public void OnGet()
        {
        }

        public void OnPost() { }

    }
}

SSO/Pages/Admin/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SSO.Models.DTOs;
using SSO.Repositpries;

namespace SSO.Pages.Admin
{
    public class LoginModel : PageModel
    {
        private readonly IUserRepository userRepository;

        public LoginModel(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }

        [BindProperty]
        public LoginDTO LoginDTO { get; set; } = default!;
        public IActionResult OnGet()
        {
            ViewData["Ref"] = base.Request.Headers.Referer;
            return Page();
        }

        

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var loginResult = userRepository.Login(LoginDTO);
            if (loginResult.Success)
            {
                return Redirect(loginResult.Data.ReturnUrl);
            }
            if (loginResult.Results.RequiresTwoFactor)
            {
                //
            }
            if (loginResult.Results.IsLockedOut)
            {
                //
            }
            ModelState.AddModelError(string.Empty, "");
            return RedirectToPage("./Login");
        }

        public async Task<IActionResult> OnGetSignOut()
        {
            userRepository.SignOut();
            return RedirectToPage("Index");
        }

    }
}

SSO/Pages/Admin/PrivilegePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SSO.Pages.Admin
{
    public class PrivilegePageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SSO/Pages/Admin/RoleManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SSO.Pages.Admin
{
    public class RoleManagementModel : PageModel
    {
        public long Id { get; set; }
        public string Mode { get; set; }

        public void OnGet(long id)
        {
            Id = id;
            Mode = "صفحه اولیه";
        }
        public void OnGetCreate(long id)
        {
            Id = id;
            Mode = "ایجاد کردن";
        }
        public void OnGetUpdate(long id)
        {
            Id = id;
            Mode = "ویرایش کردن";
        }
        public void OnGetDelete(long id)
        {
            Id = id;
            Mode = "حذف کردن";
        }
        public void OnGetRead(long id)
        {
            Id = id;
            Mode = "خواندن";
        }
        public void OnGetAddRoleToUser(long id)
        {
            Id = id;
            Mode = "تعریف کاربر برای این نقش";
        }
        public void OnGetUsersOfRole(long id)
        {
            Id = id;
            Mode = "کاربران این نقش";
        }
        public void OnGetPrivilege(long id)
        {
            Id = id;
            Mode = "مدیریت دسترسی های این نقش";
        }
    }
}

SSO/Pages/Admin/RolePage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SSO.Models.DTOs;
using SSO.Repositpries;

namespace SSO.Pages.Admin
{
    public class RolePageModel : PageModel
    {
        private readonly IRoleRepository roleRepository ;

        public RolePageModel(IRoleRepository roleRepository)
        {
            this.roleRepository = roleRepository;
        }
        public List<RoleDTO> Roles { get; set; }
        public RoleDTO RoleEntity { get; set; }
        public void OnGet()
        {
            //roleRepository.Create(new RoleDTO
            //{
            //    Name = "Admin",
            //    Description = "ادمین",
            //    IsActive = true,
            //    IsDeleted = false,
            //});
            //roleRepository.Create(new RoleDTO
            //{
            //    Name = "User",
            //    Description = "کاربر",
            //    IsActive = true,
            //    IsDeleted = false,
            //});
            Roles = roleRepository.ReadAll().Data;
        }

        public void OnPostCreate()
        {
            var res = roleRepository.Create(RoleEntity);
            if (res.Success)
            {

            }
            else
            {
                ViewData["Errors"] = res.Messages;
            }
        }
    }
}

SSO/Pages/Admin/SignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SSO.Models.DTOs;
using SSO.Repositpries;

namespace SSO.Pages.Admin
{
    public class SignUpModel : PageModel
    {
        private readonly IUserRepository userRepository;

        public SignUpModel(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }

        public IActionResult OnGet()
        {

            return Page();

        }

        [BindProperty]
        public SignUpDTO SignUpDTO { get; set; } = default!;

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await Task.Delay(100);
            var entity = new UserDTO
            {
                Name = SignUpDTO.Name,
                Family = SignUpDTO.Family,
                Email = SignUpDTO.Email,
                UserName = SignUpDTO.UserName,
                Password = SignUpDTO.Password,
                IsDeleted = false,
                IsActive= true
            };
            var res = userRepository.Create(entity);
            if (res.Success)
            {
                return RedirectToPage("./Index");
            }
            ViewData["Messages"] = res.Messages;
            return Page();
        }
    }
}

SSO/Pages/Admin/UserManagement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SSO.Models.DTOs;
using SSO.Repositpries;

namespace SSO.Pages.Admin
{
    public class UserManagementModel : PageModel
    {
        public bool ReadOnly { get; set; }
        [BindProperty]
        public long Id { get; set; }
        public string Mode { get; set; }
        private readonly IUserRepository userRepository;
        [BindProperty]
        public UserDTO UserModel { get; set; }

        [BindProperty]
        public SignUpDTO SignUpModel { get; set; }
        public UserManagementModel(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }



        public void OnGet(long id)
        {
            Id = id;
            Mode = "صفحه اولیه";
        }
        #region Create
        public void OnGetCreate()
        {
            Id = 0;
            Mode = "ایجاد کردن";
        }
        public IActionResult OnPostCreate()
        {
            if (!ModelState.IsValid)
                return Page();
            var model = new UserDTO
            {
                Name = SignUpModel.Name,
                Family = SignUpModel.Family,
                Email = SignUpModel.Email,
                UserName = SignUpModel.UserName,
                Password = SignUpModel.Password,
            };
            if (SignUpModel.Id == 0)
            {
                var result = userRepository.Create(model);
                if (result.Success)
                {
                    return RedirectToPage("UserPage");
                }
            }
            else
            {
                OnPostUpdate();
            }

            return Page();
        }
        #endregion

        #region Read
        public void OnGetRead(long id)
        {
            Id = id;
            Mode = "خواندن";
            ReadOnly = true;
            var model = userRepository.Read(id);
            UserModel = model.Data;
        }
        #endregion


        #region Update
        public void OnGetUpdate(long id)
        {
            Id = id;
            var model = userRepository.Read(id);
            SignUpModel = new SignUpDTO
            {
                Id = id,
                Name = model.Data.Name,
                Family = model.Data.Family,
                Email = model.Data.Email,
                UserName = model.Data.UserName,
                Password = model.Data.Password,

            };
            Mode = "ویرایش کردن";
        }
        public IActionResult OnPostUpdate()
        {
            var model = new UserDTO
            {
                Id = Id,
                Name = SignUpModel.Name,
                Family = SignUpModel.Family,
                Email = SignUpModel.Email,
                UserName = SignUpModel.UserName,
                Password = SignUpModel.Password,
            };
            if (!ModelState.IsValid)
            {
                return Page();
            }
            var result = userRepository.Update(model);
            if (result.Success)
            {
                return RedirectToPage("UserPage");
            }
            return Page();
        }
        #endregion


        #region Delete
        public IActionResult OnGetDelete(long id)
        {
            Id = id;
            var result =  userRepository.Delete(id);
            return RedirectToPage("UserPage");
        }
        #endregion

        #region Login
        public async Task<IActionResult> OnGetLogin(long id)
        {
            var user = userRepository.Read(id).Data;

            var login = new LoginDTO
            {
                UserName = user.UserName,
                Password = user.Password,
            };

            var res = await userRepository.LoginInternal(login);
            if (res.Success)
                return RedirectToPage("Index");
            else
                return Page();
        }
        #endregion
    }
}

SSO/Pages/Admin/UserPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SSO.Models.DTOs;
using SSO.Repositpries;

namespace SSO.Pages.Admin
{
    public class UserPageModel : PageModel
    {
        private readonly IUserRepository userRepository;

        public UserPageModel(IUserRepository userRepository)
        {
            this.userRepository = userRepository;
        }
        public List<UserDTO> Users { get; set; }
        public void OnGet()
        {
            Users = new List<UserDTO>();
            var data = userRepository.ReadAll();
            Users = data.Data.ToList();
        }
    }
}

SSO/Pages/LoginPages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SSO.Pages.LoginPages
{
    public class LoginModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SSO/Pages/SignUpPages/SignUp.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SSO.Pages
{
    public class SignUpModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

SSO/Pages/Admin/ForgotPassword.cshtml
@page
@model SSO.Pages.Admin.ForgotPasswordModel
@{
}


<form method="post">
    <input class="form-control" asp-for="Model.Name" placeholder="Name ..." />
    <input type="submit" name="submit" value="submit" />
</form>


@* @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
} *@

SSO/Pages/Admin/Login.cshtml
@page
@model SSO.Pages.Admin.LoginModel

@{
    ViewData["Title"] = "Login";
    Layout = "~/Pages/Shared/_Layout.cshtml";
    var Title = "صفحه ورود یکپارچه";
    ViewData["Title"] = Title;
    var url = ViewData["Ref"];
}

<hr />
<div class="container align-items-center pb-5">
    <div class="alert alert-success border-dark text-center display-6 shadow rounded-5">به سامانه ورود یکپارچه خوش آمدید</div>
    <div class="row d-flex flex-row justify-content-center mt-5">
        <div class="col-sm-10 col-md-8 col-lg-6 col-xs-6 bg-light bg-gradient shadow p-5 rounded-3 ">
            <div class="alert alert-success border-success text-center">@Title</div>
            <hr />
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input asp-for="LoginDTO.ReturnUrl" type="hidden" value="@url" />
                <div class="form-group">
                    <label asp-for="LoginDTO.UserName" class="form-label">نام کاربری</label>
                    <input asp-for="LoginDTO.UserName" class="form-control" />
                    <span asp-validation-for="LoginDTO.UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LoginDTO.Password" class="form-label">رمز کاربری</label>
                    <input asp-for="LoginDTO.Password" class="form-control" />
                    <span asp-validation-for="LoginDTO.Password" class="text-danger"></span>
                </div>
                <div class="form-group form-check p-2">
                    <div class="d-flex flex-row justify-content-between">
                        <div class="d-flex flex-row">
                            <input class="form-check-input mx-1" asp-for="LoginDTO.IsPersistance" />
                            <text class="mx-4">مرا به خاطر بسپار!</text>
                        </div>
                        <div>
                            <a asp-page="./ForgotPassword">رمز خود را فراموش کردم ...!</a>
                        </div>
                    </div>
                </div>
                <div class="form-group p-2 text-center mt-3">
                    <input type="submit" value="ورود یکپارچه"
                           class="btn btn-primary w-50 shadow" />
                </div>
                <div class="form-group p-2 text-center">
                    <a class="btn btn-success w-50 shadow" asp-page="./SignUp">ثبت نام</a>
                </div>
            </form>
        </div>
    </div>
</div>
@*
@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
 *@

SSO/Pages/Admin/PrivilegePage.cshtml
@page
@model SSO.Pages.Admin.PrivilegePageModel
@{
}
<div style="height:80vh; overflow:auto;" class=" container d-flex flex-column justify-content-between">
    <div class="row shadow">Row 1</div>
    <div class="row shadow">Row 2</div>
    <div class="row shadow text-center">
        <a asp-page="./AdminPanel" class="btn btn-dark text-light">مدیریت کابران</a>
    </div>
</div>

SSO/Pages/Admin/RoleManagement.cshtml
@page
@model SSO.Pages.Admin.RoleManagementModel
@{
}

<div>
    <div class="alert alert-primary shadow">@Model.Mode</div>
    @if (Model.Id != 0)
    {
        <div class="alert alert-success">اطلاعات کاربر موجود است</div>
    }
    else
    {
        <div class="alert alert-danger">موردی یافت نشده است</div>
    }
</div>

SSO/Pages/Admin/RolePage.cshtml
@page
@model SSO.Pages.Admin.RolePageModel
@{
}
<style>
    .btn-tk {
        width: 150px;
        border-radius: 1rem;
        margin:0.3px;
    }
</style>

<div style="height:80vh; overflow:auto;" class=" container-fluid d-flex flex-column justify-content-between">
    <div class="row shadow">
        <div class="text-center alert alert-primary border-primary fixed-top d-flex flex-row justify-content-between">
            <a asp-page="./RoleManagement" asp-route-id="0" asp-page-handler="Create" class="btn btn-primary">جدید</a>
            <text>مدیریت نقش کاربران</text>
        </div>
        <div>
            <table class="table table-hover text-center text-light">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>نام</th>
                        <th>توضیحات</th>
                        <th>عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Roles)
                    {
                        <tr>
                            <th>@item.Id</th>
                            <th>@item.Name</th>
                            <th>@item.Description</th>
                            <th>
                                <a asp-page="./RoleManagement" asp-route-id="@item.Id" asp-page-handler="Update" class="btn-tk btn btn-warning bg-gradient">ویرایش</a>
                                <a asp-page="./RoleManagement" asp-route-id="@item.Id" asp-page-handler="Read" class="btn-tk btn btn-info bg-gradient">نمایش</a>
                                <a asp-page="./RoleManagement" asp-route-id="@item.Id" asp-page-handler="Delete" class="btn-tk btn btn-danger bg-gradient">حدف</a>
                                <a asp-page="./RoleManagement" asp-route-id="@item.Id" asp-page-handler="AddRoleToUser" class="btn-tk btn btn-primary bg-gradient">معرفی به کاربران</a>
                                <a asp-page="./RoleManagement" asp-route-id="@item.Id" asp-page-handler="UsersOfRole" class="btn-tk btn btn-info bg-gradient">کاربران این نقش</a>
                                <a asp-page="./RoleManagement" asp-route-id="@item.Id" asp-page-handler="Privilege" class="btn-tk btn btn-dark bg-gradient">مدیریت دسترسی</a>
                            </th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
    @if (@ViewData["Errors"] != null)
    {
        <div class="alert alert-danger">@ViewData["Errors"]</div>
    }
    <div class="row shadow text-center">
        <a asp-page="./AdminPanel" class="btn btn-dark text-light fixed-bottom p-3">مدیریت کابران</a>
    </div>
</div>

SSO/Pages/Admin/SignUp.cshtml
@page
@model SSO.Pages.Admin.SignUpModel

@{
    ViewData["Title"] = "SignUp";
    Layout = "~/Pages/Shared/_Layout.cshtml";
    var Title = "ثبت اطلاعات کاربر جدید";
    ViewData["Title"] = Title;
    var messages = ViewData["Messages"];
}

<hr />
<div class="container align-items-center pb-5">
    <div class="alert alert-primary border-dark text-center display-6 shadow rounded-5">به سامانه ورود یکپارچه خوش آمدید</div>
    <div class="row d-flex flex-row justify-content-center mt-5">
        <div class="col-md-8 col-sm-10 col-xl-6 col-lg-8 bg-light bg-gradient shadow p-5 rounded-3 ">
            <div class="alert alert-success border-success text-center">@Title</div>
            <hr />
            @if (messages != null)
            {
                <div class="alert alert-danger shadow text-center">
                    @messages
                </div>
            }
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="SignUpDTO.Name" class="form-label">نام</label>
                    <input asp-for="SignUpDTO.Name" class="form-control" />
                    <span asp-validation-for="SignUpDTO.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignUpDTO.Family" class="form-label">فامیلی</label>
                    <input asp-for="SignUpDTO.Family" class="form-control" />
                    <span asp-validation-for="SignUpDTO.Family" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignUpDTO.UserName" class="form-label">نام کاربری</label>
                    <input asp-for="SignUpDTO.UserName" class="form-control" />
                    <span asp-validation-for="SignUpDTO.UserName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignUpDTO.Email" class="form-label">ایمیل</label>
                    <input asp-for="SignUpDTO.Email" class="form-control" />
                    <span asp-validation-for="SignUpDTO.Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignUpDTO.Password" class="form-label">رمز</label>
                    <input asp-for="SignUpDTO.Password" class="form-control" />
                    <span asp-validation-for="SignUpDTO.Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SignUpDTO.ConfirmPassword" class="form-label">تکرار رمز</label>
                    <input asp-for="SignUpDTO.ConfirmPassword" class="form-control" />
                    <span asp-validation-for="SignUpDTO.ConfirmPassword" class="text-danger"></span>
                </div>


                <div class="form-group text-center p-2 mt-4 d-flex flex-row justify-content-around">
                    <input type="submit"
                           value="ثبت نام"
                           class="btn btn-success w-25 shadow" />
                    <a class="btn btn-primary w-25 shadow"
                       asp-page="./Login">ورود</a>
                </div>

            </form>
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

SSO/Pages/Admin/UserManagement.cshtml
@page "{id}"
@model SSO.Pages.Admin.UserManagementModel
@{
    var Title = "ثبت اطلاعات کاربر جدید";
    ViewData["Title"] = Title;
    var messages = ViewData["Messages"];
}
<style>
    .title-tk {
        width: 150px;
        background: linear-gradient(270deg, #ffffff3d, transparent);
        padding: 0.5rem;
        border-radius: 1rem;
    }

    .value-tk {
        padding: 0.5rem;
        border-radius: 1rem;
    }

    .field-tk{
        margin: 1rem;
        box-shadow: 0 0 8px 3px #0000002e;
        padding: 5px;
        border-radius: 1rem;
        color: wheat;
        display:flex;
        flex-direction:row;
    }
</style>

<div>
    @if (Model.ReadOnly)
    {
        <div class="container ">
            <div class="row">
                <div class="field-tk ">
                    <div class="title-tk">نام</div>   <div class="value-tk">@Model.UserModel.Name</div>
                </div>
                <div class="field-tk ">
                    <div class="title-tk">فامیلی</div>   <div class="value-tk">@Model.UserModel.Family</div>
                </div>
                <div class="field-tk ">
                    <div class="title-tk">ایمیل</div>   <div class="value-tk">@Model.UserModel.Email</div>
                </div>
                <div class="field-tk ">
                    <div class="title-tk">نام کاربری</div>   <div class="value-tk">@Model.UserModel.UserName</div>
                </div>
                <div class="field-tk ">
                    <div class="title-tk">رمز کاربری</div>   <div class="value-tk">@Model.UserModel.Password</div>
                </div>
                <div class="field-tk ">
                    <div class="title-tk">تلفن</div>   <div class="value-tk">@Model.UserModel.Phone</div>
                </div>
            </div>
            <div>
                <a asp-page="./UserPage" class="btn btn-primary bg-gradient rounded">بازگشت به صفحه قبل</a>
            </div>
        </div>
    }
    else
    {
        <div class="container align-items-center pb-5">
            <div class="alert alert-primary border-dark text-center display-6 shadow rounded-5">به سامانه ورود یکپارچه خوش آمدید</div>
            <div class="row d-flex flex-row justify-content-center mt-5">
                <div class="col-md-8 col-sm-10 col-xl-6 col-lg-8 bg-light bg-gradient shadow p-5 rounded-3 ">
                    @if (messages != null)
                    {
                        <div class="alert alert-danger shadow text-center">
                            @messages
                        </div>
                    }
                    <form method="post">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="SignUpModel.Name" class="form-label">نام</label>
                            <input asp-for="SignUpModel.Name" class="form-control" />
                            <input type="hidden" value="@Model.Id" class="form-control" />
                            <span asp-validation-for="SignUpModel.Name" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SignUpModel.Family" class="form-label">فامیلی</label>
                            <input asp-for="SignUpModel.Family" class="form-control" />
                            <span asp-validation-for="SignUpModel.Family" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SignUpModel.UserName" class="form-label">نام کاربری</label>
                            <input asp-for="SignUpModel.UserName" class="form-control" />
                            <span asp-validation-for="SignUpModel.UserName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SignUpModel.Email" class="form-label">ایمیل</label>
                            <input asp-for="SignUpModel.Email" class="form-control" />
                            <span asp-validation-for="SignUpModel.Email" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SignUpModel.Password" class="form-label">رمز</label>
                            <input asp-for="SignUpModel.Password" class="form-control" />
                            <span asp-validation-for="SignUpModel.Password" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="SignUpModel.ConfirmPassword" class="form-label">تکرار رمز</label>
                            <input asp-for="SignUpModel.ConfirmPassword" class="form-control" />
                            <span asp-validation-for="SignUpModel.ConfirmPassword" class="text-danger"></span>
                        </div>


                        <div class="form-group text-center p-2 mt-4 d-flex flex-row justify-content-around">
                            <input type="submit"
                                   value="ثبت نام"
                                   class="btn btn-success w-25 shadow" />
                        </div>

                    </form>
                </div>
            </div>
        </div>

    }
</div>

SSO/Pages/Admin/UserPage.cshtml
@page
@model SSO.Pages.Admin.UserPageModel
@{
}

<div style="height:80vh; overflow:auto;" class=" container-fluid d-flex flex-column justify-content-between">
    <div class="row shadow">
        <div class="text-center alert alert-primary border-primary fixed-top d-flex flex-row justify-content-between">
            <a asp-page="./UserManagement" asp-route-id="0"  asp-page-handler="Create" class="btn btn-primary">جدید</a>
            <text>مدیریت کاربران</text>
        </div>
        <div>
            <table class="table table-hover text-center text-light">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>نام</th>
                        <th>فامیل</th>
                        <th>نام کاربری</th>
                        <th>ایمیل</th>
                        <th>رمز</th>
                        <th>تلفن</th>
                        <th>عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Users)
                    {
                        <tr>
                            <th>@item.Id</th>
                            <th>@item.Name</th>
                            <th>@item.Family</th>
                            <th>@item.UserName</th>
                            <th>@item.Email</th>
                            <th>@item.Password</th>
                            <th>@item.Phone</th>
                            <th>
                                <a asp-page="./UserManagement" asp-route-id="@item.Id" asp-page-handler="Update" class="btn btn-warning">ویرایش</a>
                                <a asp-page="./UserManagement" asp-route-id="@item.Id" asp-page-handler="Read" class="btn btn-info">نمایش</a>
                                <a asp-page="./UserManagement" asp-route-id="@item.Id" asp-page-handler="Delete" class="btn btn-danger">حدف</a>
                                <a asp-page="./UserManagement" asp-route-id="@item.Id" asp-page-handler="Login" class="btn btn-primary">ورود</a>
                            </th>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

    <div class="row shadow text-center">
        <a asp-page="./AdminPanel" class="btn btn-dark text-light fixed-bottom p-3">مدیریت کابران</a>
    </div>
</div>